//
//  Answer.swift
//  Brain Damage
//
//  Created by Marcelo de Araújo on 05/10/2023.
//

final class Answer {
    static let shared = Answer()

    let flags = [
        "England",
        "Abkhazia",
        "Australia",
        "Austria",
        "Albania",
        "Algeria",
        "Angola",
        "Andorra",
        "Antigua and Barbuda",
        "Argentina",
        "Armenia",
        "Afghanistan",
        "Bahamas",
        "Bangladesh",
        "Barbados",
        "Belarus",
        "Belize",
        "Belgium",
        "Benin",
        "Bulgaria",
        "Bolivia",
        "Bosnia and Herzegovina",
        "Botswana",
        "Brazil",
        "Burkina Faso",
        "Burundi",
        "Butane",
        "Vanuatu",
        "Vatican",
        "United Kingdom",
        "Hungary",
        "Venezuela",
        "Vietnam",
        "Gabon",
        "Haiti",
        "Gambia",
        "Ghana",
        "Guatemala",
        "Guinea",
        "Guinea-Bissau",
        "Germany",
        "Gibraltar",
        "Honduras",
        "Hong Kong",
        "Grenada",
        "Greenland",
        "Greece",
        "Georgia",
        "Denmark",
        "Djibouti",
        "Dominica",
        "Dominican Republic",
        "Egypt",
        "Zambia",
        "Zimbabwe",
        "Israel",
        "India",
        "Indonesia",
        "Jordan",
        "Iraq",
        "Iran",
        "Ireland",
        "Iceland",
        "Spain",
        "Italy",
        "Cape Verde",
        "Kazakhstan",
        "Cambodia",
        "Cameroon",
        "Canada",
        "Qatar",
        "Kenya",
        "Cyprus",
        "Kyrgyzstan",
        "Kiribati",
        "DPRK",
        "Colombia",
        "Comoros",
        "Congo",
        "Kingdom of Eswatini",
        "Costa Rica",
        "Côte d'Ivoire",
        "Cuba",
        "Laos",
        "Latvia",
        "Lesotho",
        "Liberia",
        "Lebanon",
        "Libya",
        "Lithuania",
        "Luxembourg",
        "Mauritania",
        "Madagascar",
        "Macedonia",
        "Malawi",
        "Mali",
        "Republic of Maldives",
        "Malta",
        "Morocco",
        "Marshall Islands",
        "Mexico",
        "Micronesia",
        "Mozambique",
        "Moldavia",
        "Monaco",
        "Mongolia",
        "Myanmar",
        "Namibia",
        "Nauru",
        "Nigeria",
        "Netherlands",
        "Nicaragua",
        "New Zealand",
        "Norway",
        "UAE",
        "Oman",
        "Pakistan",
        "Palau",
        "Palestine",
        "Panama",
        "Papua New Guinea",
        "Peru",
        "Poland",
        "Portugal",
        "Puerto Rico",
        "Russian Federation",
        "Salvador",
        "Samoa",
        "San Marino",
        "Sao Tome and Principe",
        "Saudi Arabia",
        "Senegal",
        "Saint Vincent and the Grenadines",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Serbia",
        "Singapore",
        "Syria",
        "Slovakia",
        "Slovenia",
        "Solomon islands",
        "Somalia",
        "Sudan",
        "Suriname",
        "USA",
        "Sierra Leone",
        "Tajikistan",
        "Thailand",
        "Tanzania",
        "Togo",
        "Tonga",
        "Trinidad and Tobago",
        "Tuvalu",
        "Tunisia",
        "Turkmenistan",
        "Türkiye",
        "Uganda",
        "Uzbekistan",
        "Ukraine",
        "Wales",
        "Faroe islands",
        "Fiji",
        "Philippines",
        "Finland",
        "France",
        "Croatia",
        "Chad",
        "Montenegro",
        "Czech Republic",
        "Chile",
        "Sweden",
        "Sri Lanka",
        "Scotland",
        "Ecuador",
        "Equatorial Guinea",
        "Eritrea",
        "Estonia",
        "Ethiopia",
        "The Republic of Korea",
        "SOUTH AFRICA",
        "South Ossetia",
        "Japan"
    ]

    let movies = [
        "The Agents of U.N.C.L.E.",
        "A Bronx Tale",
        "Batman Begins",
        "Gangster",
        "Heroes",
        "Gladiator",
        "Race",
        "Twenty One",
        "Gentlemen",
        "John Wick",
        "Johnny D.",
        "Donnie Brasco",
        "Get The Knives",
        "Scent Of A Woman",
        "A Star Is Born",
        "Green Book",
        "Green Mile",
        "Meet Joe Black",
        "Zoo",
        "The Imitation Game",
        "A game",
        "Mind games",
        "The Bourne Identity",
        "Interstellar",
        "Personnel",
        "Casino",
        "Gorgeous",
        "Legend",
        "Face With A Scar",
        "Martian",
        "Matrix",
        "Reality Changers",
        "Mission Impossible",
        "Silence Of The Lambs",
        "Back To The Future",
        "Start",
        "Knockdown",
        "Areas Of Darkness",
        "Gifted",
        "Obsession",
        "Once Upon Time In America",
        "Once Upon A Time In Hollywood",
        "Office",
        "The Shawshank Redemption",
        "Train To Yuma",
        "Made In America",
        "Good Guys",
        "Social Network",
        "Trainee",
        "Steve Jobs",
        "Fight",
        "Terminal",
        "Terminator",
        "Transformers",
        "Gone In 60 Seconds",
        "Good Will Hunting",
        "Forrest Gump",
        "Rain Man",
        "Ford vs Ferrari",
        "Top Gun"
    ]
    private init() {}
}
